version: '3.8'

services:
  app:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    container_name: lucky-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - lucky-network
    depends_on:
      - database
      - redis

  nginx:
    image: nginx:alpine
    container_name: lucky-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lucky-network
    depends_on:
      - app

  database:
    image: postgres:15-alpine
    container_name: lucky-postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - lucky-network

  redis:
    image: redis:alpine
    container_name: lucky-redis
    ports:
      - "6379:6379"
    networks:
      - lucky-network

networks:
  lucky-network:
    driver: bridge

volumes:
  postgres_data:
